import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const banner ={
    transform: 'translate3d(0, 570.413, 0)',
    position: 'absolute',
    height: 1194,
    width: 1792,
    maxWidth: 'none'
  
}
const parallax = {
  visibility: 'visible',
  zIndex: -100,
  position: 'fixed', 
  top: 0,
  left: 0, 
  overflow: 'hidden',  
  height: 814, 
  width: 1792
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className="sectino1 parallax-container parallax-home parallax_gen" id="Section-1" data-natural-width="1000" data-parallax="scroll" data-position="top right" data-bleed="1" data-image-src="https://d3o47ov0yc40fm.cloudfront.net/upload/homebgntiny.webp" data-mirror-container="#Section-1">
        <div className="parallax-mirror" style={parallax}><img className="parallax-slider" src="https://d3o47ov0yc40fm.cloudfront.net/upload/homebgntiny.webp" style={banner} /></div>
        <div className="container s2">
          <div className="Form-Section-1">

            <h2 className="rotatetxting fs1h3">A better way to order Pizza
            </h2>
            <p>Delivery Address</p>
            <button className="btn-search-sec1">Search</button>
            <p>
              <span>
                <a className="cp btnfilt" data-target="#loginfrmmaster" data-toggle="modal">Login</a>
              </span>
              for your recent addresses.
            </p>
          </div>
          <a className="sphome cp" href="/browse">view popular restaurants and stores </a>
        </div>
        </div>
      </main>
    </>
  )
}
